# Your Solution
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: tejasit722week7.azurecr.io/book_catalog:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7000
        env:
        - name: PORT
          value: "7000"
        - name: DATABASE_URL
          value: "postgresql://pavanteja_sit722_part3_user:rYIO3yjWLxdhlFO9vBqX78q3JCCEdbYm@dpg-crsia80gph6c738tsb0g-a.oregon-postgres.render.com/pavanteja_sit722_part3"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - port: 7000
      targetPort: 7000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers: 
      - name: inventory-management
        image: tejasit722week7.azurecr.io/inventory_management:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7001
        env:
        - name: PORT
          value: "7001"
        - name: DATABASE_URL
          value: "postgresql://pavanteja_sit722_part3_user:rYIO3yjWLxdhlFO9vBqX78q3JCCEdbYm@dpg-crsia80gph6c738tsb0g-a.oregon-postgres.render.com/pavanteja_sit722_part3"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - port: 7001
      targetPort: 7001